### PR TITLE
wrap-text

### LINKED ISSUE #242: better wrapping text
add text wrap to headlines and body

### PR DESCRIPTION
**Pull request by sforschen**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #242

Test URLs:
- Before: https://main--elixirsolutions--hlxsites.hlx.live/
- After: https://pretty-text--elixirsolutions--hlxsites.hlx.live/

### CODE REVIEW

**Comment by sforschen** [comment]
@janefrommaine I was watching a CSS video about text and was like I bet this will make the text on the site look better.

I tested it this morning, and it just cleans up the line breaks to a much nicer cadence.

**Review by janefrommaine — COMMENTED** [review]
@sforschen Very nice! I really like how text-wrap balance looks on the headings & I'll probably try adding it to the portal too!

As for text-wrap pretty, I'm not spotting where that makes an impact, can you point out some specific examples so I can take a look?

I've read how pretty has less support in browsers like Firefox https://developer.mozilla.org/en-US/docs/Web/CSS/text-wrap#browser_compatibility so I'm wondering if it is worth the potential performance hit mentioned here - https://developer.mozilla.org/en-US/docs/Web/CSS/text-wrap#pretty

**Comment by sforschen** [comment]
@janefrommaine ah  yeah pretty is a little more subtle. It for the most part cleans up orphans in the body copy. While it doesn't have as much support it helps us author content that is easier to read and looks better. I often have Stephanie rewrite content if it leaves an orphan and looks bad. It also helps on mobile. The vast majority of our traffic is Chrome and Edge. 
On the about us page:
image
Weightloss blog:
image

**Review by janefrommaine — APPROVED** [review]
Looks great, thanks for sharing those examples!  
Just realized that it also helps in the rare instances when the breadcrumb needs to wrap at some breakpoints. Very nice.

**Pull request merged**
