### PR TITLE
Add pdf indicator to hyperlinks to pdfs. Also update these links to o…

### LINKED ISSUE #146: Add (PDF)  some sort of indicator to indicate PDF links
Add (PDF)  some sort of indicator to indicate PDF links

### PR DESCRIPTION
**Pull request by janefrommaine**
…pen in a new tab.

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #146

Test URLs:
- Before: https://main--elixirsolutions--hlxsites.hlx.live/
- After: https://pdf-indicator--elixirsolutions--hlxsites.hlx.live/

### CODE REVIEW

**Review by sforschen — CHANGES_REQUESTED** [review]
@janefrommaine not sure why but the footer is pulling in (PDF), the logo image too which is weird.

**Comment by janefrommaine** [comment]
@sforschen, haha yeah this is a weird bug related to the branch url having the string "pdf" in it - "pdf-indicator".
I'll work on fixing the regex match so it only looks for the file extension and not the domain or other parts of the url.

**Comment by janefrommaine** [comment]
@sforschen, that issue should be fixed now.

A couple questions I wanted to get your feedback on...

1. There are some places where we have a link and a period at the end - https://pdf-indicator--elixirsolutions--hlxsites.hlx.live/aboutus/compliance-and-ethics 
"Click here to download our Code of Conduct."
For these cases, should we remove the "." so it doesn't look weird when "(PDF)" is added?

2. More of an observation, but there are some pages with lots of PDF links and it is a mix of external and internal
https://pdf-indicator--elixirsolutions--hlxsites.hlx.live/providers
Do we eventually plan to have the majority of the external links copied to be internal? I think these are mostly Hubspot links

Let me know if you notice anything else odd.

**Comment by sforschen** [comment]
@janefrommaine 

I just fixed number 1 which definitely looked odd.

For number 2 yes the goal is to get those links off a third-party site. Since most are forms if we can get some sort of secure on-site solution or get formstack to work on-site that would solve it.

**Review by sforschen — APPROVED** [review]

**Review by sforschen — APPROVED** [review]

**Pull request merged**
